### PR TITLE
Fix jackface dance

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by CalmBum** [comment]
Did you put the CalmBum folder in the lib folder or the resources folder? It* should go into lib

**Comment by Sainan** [comment]
I didn't put it anywhere. The issue is with your auto-updater config. And it _should_ be in the resources folder, because it's a resource, not a lib.

**Comment by CalmBum** [comment]
Ahhhh I see. Thank you for clearing that up

**Comment by Sainan** [comment]
Just FYI, you still haven't fixed your auto-updater config.

**Pull request closed without merging**
